# Generated by Django 4.1.13 on 2024-06-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tema',
            table='TEMA',
        ),
    ]
