# Generated by Django 5.0.6 on 2024-06-20 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='numeroSale',
        ),
        migrations.AlterField(
            model_name='tema',
            name='codice',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('temaSala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='main.tema')),
            ],
        ),
    ]
